// Generated by https://quicktype.io

import { LogLevel } from "./logger";

export type ClashDashBoard = {
    [id: string]: {
        url: string,
        dest: string,
        root?: string
    }
}
export interface AppConfig {
    log: keyof typeof LogLevel
    "curl": { [id: string]: string };
    "profiles": {
        "folder": string,
        "branch": string,
        "repository": string,
    },
    "ui": ClashDashBoard
}

const default_config: AppConfig = {
    log: "info",
    curl: {
        "location": ""
    },
    profiles: {
        folder: "{home}/.config/uclash/clash/",
        branch: "main",
        repository: ""
    },
    ui: {
        "yacd": {
            url: "https://github.com/haishanh/yacd/archive/gh-pages.zip",
            dest: "{home}/.config/uclash/yacd",

        },
        "ui": {
            url: "https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip",
            dest: "{home}/.config/uclash/cd",
            root: "clash-dashboard-gh-pages/"
        }
    }
}

export default default_config;