// Generated by https://quicktype.io

import { LogLevel } from "./logger";

export interface AppConfig {
    log:keyof typeof LogLevel
    "curl": { [id: string]: string };
    "profiles": {
        "folder": string,
        "branch": string,
        "repository": string,
    }
}

const default_config: AppConfig = {
    log:"info",
    curl: {
        "location":""
    },
    profiles: {
        folder: "{HOME}/.config/uclash/clash/",
        branch: "main",
        repository: ""
    }
}

export default default_config;