// Generated by https://quicktype.io

import { LogLevel } from "./logger";

export type ClashDashBoards = {
    [id: string]: {
        url: string,
        dest: string,
        root?: string
    }
}
export type PublicIpProviders = {
    [id: string]: {
        url: string,
        type: "json" | "text"
    }
}

export interface AppConfig {
    log: keyof typeof LogLevel
    "curl": { [id: string]: string };
    "profiles": {
        "folder": string,
        "branch": string,
        "repository": string,
    },
    "ui": ClashDashBoards,
    "ip": PublicIpProviders
}

const default_config: AppConfig = {
    log: "info",
    curl: {
        "location": ""
    },
    profiles: {
        folder: "{home}/.config/clash/",
        branch: "main",
        repository: ""
    },
    ui: {
        "yacd": {
            url: "https://github.com/haishanh/yacd/archive/gh-pages.zip",
            dest: "{home}/.config/uclash/yacd",
            root: "yacd-gh-pages/"

        },
        "ui": {
            url: "https://github.com/Dreamacro/clash-dashboard/archive/gh-pages.zip",
            dest: "{home}/.config/uclash/cd",
            root: "clash-dashboard-gh-pages/"
        }
    },
    ip: {
        "ipip": {
            url: "http://myip.ipip.net",
            type: "text"
        },
        "myip": {
            url: "https://api.myip.la/en?json",
            type: "json"
        },
        "myipCn": {
            url: "https://api.myip.la/cn?json",
            type: "json"
        }
    }
}

export default default_config;