# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn

      - name: "generate cache files"
        run: |
          node bin/uclash.js -V
          node bin/uclash.js init
          node bin/uclash.js generate 0
          
      - name: "install clash"
        run: |
          mkdir ./tmp/
          bash scripts/install-clash.sh ./tmp/
          ./tmp/clash -t -f ./tmp/0.yml
              
      - name: "test"
        run: |
          node bin/uclash.js  config ui-folder {project}/tmp
          echo clash.razord.top/ >> tmp/CNAME
          node bin/uclash.js  exec 0 --dryrun
          node bin/uclash.js  exec 0 --dryrun --daemon screen
          node bin/uclash.js  find
          node bin/uclash.js  ip
          
      - run: yarn publish
        if: success() && startsWith( github.ref, 'refs/tags/') 
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
