# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - v*
  pull_request:
    branches:
      - v*
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: "*"

      - name: "build"
        run: |
          pnpm build
              
      - name: "test"
        run: |
          node bin/uclash.js generate x1
          mkdir ./tmp/
          bash scripts/install-clash.sh ./tmp/
          ./tmp/clash -t -f ./tmp/0.yml
          node bin/uclash.js  ip
          
      - run: pnpm publish
        if: success() && startsWith( github.ref, 'refs/tags/') 
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
